### ISSUE TITLE
Question: Do you accept Pull Requests ?

### ISSUE THREAD

**Issue by tweakbsd** [TeamDraco/RavageAndCabbage#3]
Hi there, just found your mod and find it very cool and interesting. Especially now that you're going to add Horn Armor. 
I read a comment in the code in RCRavagerEntity.java "There must be a better way to do this" for applying armor to the Entity. 
Indeed there is, and if you're ok with it  I'll make a PR for it in the next 1-2days. Crafting recipes for horn armor is also missing as of now. I honestly have no clue what would be a fitting pattern. Maybe giving them as loot only is best. And make diamond upgradable to netherite in a smithing table ?!? Just ideas...

Hope to hearing from you soon, btw, sorry to spam your Issues with this question. Feel free to delete it if you don't like it.

**Comment by Coda1552** [comment]
Hello, a PR would be great, thank you! Horn armor will likely be just like horse armor, with leather being craftable but the others being loot only. Don't worry about spam, this is very helpful!

**Comment by tweakbsd** [comment]
👍🏼 Thank you very much, sounds great! Let me make my PR first then we can talk about discord later. 
I'm almost done with the PR for it to be submitted.

**Comment by tweakbsd** [comment]
PR is made as #4 :-) hope it helps a little bit.

**Comment by Coda1552** [comment]
Thank you so much!
